### PR TITLE
Add band name Emotions of the Post-Apocalypse and album Implicit Winking

### PR DESCRIPTION
**Pull request by gigawhitlocks**

### CODE REVIEW

**Comment by ndcampbell** [comment]
Where are the test cases?

**Comment by gigawhitlocks** [comment]
HOW DO I TEST THIS

**Comment by ndcampbell** [comment]
mock human eyes and assert that they have the ability to read it

**Comment by vsinha** [comment]
plx manually update the 'last updated' timestamp

**Pull request merged**
